<?php
// Shared car data — each entry drives the car-page.php template.
return [
    'Audi-A6-Sportback-e-tron' => [
        'filename' => 'Audi-A6-Sportback-e-tron',
        'page_title' => 'Audi A6 Sportback e-tron — EcoDrive',
        'page_desc'  => 'Audi A6 Sportback e-tron, berline électrique premium avec 700 plus km d\'autonomie. Essai gratuit EcoDrive.',
        'page_url'   => 'voitures/Audi-A6-Sportback-e-tron.php',
        'page_image' => 'images/audi-a6-sportback-e-tron-electrique/essai-audi-a6-sportback-e-tron-la-grande-routiere-allemande-passe-au-tout-electrique-107381.webp',
        'jsonld' => ['brand' => 'Audi', 'price' => '239000'],
        'breadcrumb' => 'Audi A6 Sportback e-tron',
        'slider' => ['dir' => 'images/audi-a6-sportback-e-tron-electrique/', 'img' => 'essai-audi-a6-sportback-e-tron-la-grande-routiere-allemande-passe-au-tout-electrique-107381.webp', 'alt' => 'Audi A6 Sportback e-tron'],
        'price_display' => '239 000',
        'car_id' => 1,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '367', 'unit' => 'ch', 'sub' => '270 kW'],
            ['label' => 'Batterie',  'value' => '100',  'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '757', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '5,4', 'unit' => 's', 'sub' => '210 km/h'],
            ['label' => 'Poids',     'value' => '2 175','unit' => 'kg', 'sub' => 'Coffre 502 L'],
        ],
        'specs_motorisation' => ['367 ch (270 kW)', '565 Nm', 'Propulsion (RWD)', '210 km/h'],
        'specs_batterie' => [
            'capacite' => '100 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '757 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '100 kWh', 'battery_fill' => '92%',
        ],
        'specs_recharge' => ['9 h 10 (11 kW)', '21 min (10-80%, 270 kW)'],
        'specs_dimensions' => ['4 960 mm', '1 960 mm', '1 450 mm', '502 L'],
    ],
    'BMW-iX3' => [
        'filename' => 'BMW-iX3',
        'page_title' => 'BMW iX3 — EcoDrive',
        'page_desc'  => 'BMW iX3, SUV électrique avec 460 km d\'autonomie et technologie eDrive. Découvrez-le chez EcoDrive.',
        'page_url'   => 'voitures/BMW-iX3.php',
        'page_image' => 'images/bmw-ix3/BMW-iX3.jpg',
        'jsonld' => ['brand' => 'BMW', 'price' => '249900'],
        'breadcrumb' => 'BMW iX3 2026',
        'slider' => ['dir' => 'images/bmw-ix3/', 'img' => 'BMW-iX3.jpg', 'alt' => 'BMW iX3'],
        'price_display' => '249 900',
        'car_id' => 2,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '469', 'unit' => 'ch', 'sub' => '345 kW'],
            ['label' => 'Batterie',  'value' => '108,7','unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '805', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '4,9', 'unit' => 's', 'sub' => '225 km/h'],
            ['label' => 'Poids',     'value' => '2 265','unit' => 'kg', 'sub' => 'Coffre 540 L'],
        ],
        'specs_motorisation' => ['469 ch (345 kW)', '700 Nm', 'Intégrale (xDrive)', '225 km/h'],
        'specs_batterie' => [
            'capacite' => '108,7 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '805 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '108.7 kWh', 'battery_fill' => '100%',
        ],
        'specs_recharge' => ['8 h 15 (11 kW)', '21 min (10-80%, 400 kW)'],
        'specs_dimensions' => ['4 755 mm', '2 020 mm', '1 665 mm', '540 L'],
    ],
    'BYD-Atto-3' => [
        'filename' => 'BYD-Atto-3',
        'page_title' => 'BYD Atto 3 — EcoDrive',
        'page_desc'  => 'BYD Atto 3, SUV compact électrique au design audacieux. Autonomie 420 km WLTP. Réservez votre essai.',
        'page_url'   => 'voitures/BYD-Atto-3.php',
        'page_image' => 'images/byd-atto-3/byd-atto-3.webp',
        'jsonld' => ['brand' => 'BYD', 'price' => '123990'],
        'breadcrumb' => 'BYD Atto 3',
        'slider' => ['dir' => 'images/byd-atto-3/', 'img' => 'byd-atto-3.webp', 'alt' => 'BYD Atto 3'],
        'price_display' => '123 990',
        'car_id' => 3,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '313', 'unit' => 'ch', 'sub' => '230 kW'],
            ['label' => 'Batterie',  'value' => '74,8', 'unit' => 'kWh', 'sub' => 'Blade LFP'],
            ['label' => 'Autonomie', 'value' => '510', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '5,5', 'unit' => 's', 'sub' => '180 km/h'],
            ['label' => 'Poids',     'value' => '1 850','unit' => 'kg', 'sub' => 'Coffre 440 L'],
        ],
        'specs_motorisation' => ['313 ch (230 kW)', '480 Nm', 'Propulsion (RWD)', '180 km/h'],
        'specs_batterie' => [
            'capacite' => '74,8 kWh', 'type' => 'Blade LFP', 'autonomie' => '510 km',
            'extra_name' => 'Architecture', 'extra_value' => '800V',
            'battery_kwh' => '74.8 kWh', 'battery_fill' => '69%',
        ],
        'specs_recharge' => ['7 h (11 kW)', '25 min (10-80%, 220 kW)'],
        'specs_dimensions' => ['4 455 mm', '1 875 mm', '1 615 mm', '440 L'],
    ],
    'BYD-Dolphin' => [
        'filename' => 'BYD-Dolphin',
        'page_title' => 'BYD Dolphin — EcoDrive',
        'page_desc'  => 'BYD Dolphin, citadine électrique accessible et polyvalente. Autonomie jusqu\'à 427 km. Découvrez-la chez EcoDrive.',
        'page_url'   => 'voitures/BYD-Dolphin.php',
        'page_image' => 'images/byd-dolphin/byd-dolphin-surf-38.88-kwh-102711.webp',
        'jsonld' => ['brand' => 'BYD', 'price' => '55000'],
        'breadcrumb' => 'BYD Dolphin Surf',
        'slider' => ['dir' => 'images/byd-dolphin/', 'img' => 'byd-dolphin-surf-38.88-kwh-102711.webp', 'alt' => 'BYD Dolphin Surf'],
        'price_display' => '55 000',
        'car_id' => 4,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '156', 'unit' => 'ch', 'sub' => '115 kW'],
            ['label' => 'Batterie',  'value' => '43,2', 'unit' => 'kWh', 'sub' => 'Blade LFP'],
            ['label' => 'Autonomie', 'value' => '310', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '9,1', 'unit' => 's', 'sub' => '160 km/h'],
            ['label' => 'Poids',     'value' => '1 350','unit' => 'kg', 'sub' => 'Coffre 345 L'],
        ],
        'specs_motorisation' => ['156 ch (115 kW)', '220 Nm', 'Traction (FWD)', '160 km/h'],
        'specs_batterie' => [
            'capacite' => '43,2 kWh', 'type' => 'Blade LFP', 'autonomie' => '310 km',
            'extra_name' => 'Consommation', 'extra_value' => '13,8 kWh/100 km',
            'battery_kwh' => '43.2 kWh', 'battery_fill' => '40%',
        ],
        'specs_recharge' => ['4 h 30 (7,4 kW)', '30 min (10-80%, 85 kW)'],
        'specs_dimensions' => ['3 990 mm', '1 755 mm', '1 580 mm', '345 L'],
    ],
    'kia-ev3' => [
        'filename' => 'kia-ev3',
        'page_title' => 'Kia EV3 — EcoDrive',
        'page_desc'  => 'Kia EV3, crossover électrique avec design futuriste et autonomie impressionnante. Réservez votre essai.',
        'page_url'   => 'voitures/kia-ev3.php',
        'page_image' => 'images/kia-ev3/kia-ev3.png',
        'jsonld' => ['brand' => 'Kia', 'price' => '104980'],
        'breadcrumb' => 'Kia EV3',
        'slider' => ['dir' => 'images/kia-ev3/', 'img' => 'kia-ev3.png', 'alt' => 'Kia EV3'],
        'price_display' => '104 980',
        'car_id' => 5,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '204', 'unit' => 'ch', 'sub' => '150 kW'],
            ['label' => 'Batterie',  'value' => '81,4', 'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '605', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '7,5', 'unit' => 's', 'sub' => '170 km/h'],
            ['label' => 'Poids',     'value' => '1 790','unit' => 'kg', 'sub' => 'Coffre 460 L'],
        ],
        'specs_motorisation' => ['204 ch (150 kW)', '283 Nm', 'Traction (FWD)', '170 km/h'],
        'specs_batterie' => [
            'capacite' => '81,4 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '605 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '81.4 kWh', 'battery_fill' => '75%',
        ],
        'specs_recharge' => ['7 h (11 kW)', '31 min (10-80%, 128 kW)'],
        'specs_dimensions' => ['4 300 mm', '1 850 mm', '1 560 mm', '460 L'],
    ],
    'mercedes-classe-c-2026' => [
        'filename' => 'mercedes-classe-c-2026',
        'page_title' => 'Mercedes Classe C 2026 — EcoDrive',
        'page_desc'  => 'Mercedes Classe C 2026, berline électrique de luxe. Design, technologie et performance.',
        'page_url'   => 'voitures/mercedes-classe-c-2026.php',
        'page_image' => 'images/mercedes-classe-c-2026/1-Mercedes-Benz-Classe-C-2026.jpg',
        'jsonld' => ['brand' => 'Mercedes-Benz', 'price' => '320000'],
        'breadcrumb' => 'Mercedes-Benz Classe C 2026',
        'slider' => ['dir' => 'images/mercedes-classe-c-2026/', 'img' => '1-Mercedes-Benz-Classe-C-2026.jpg', 'alt' => 'Mercedes-Benz Classe C 2026'],
        'price_display' => '320 000',
        'car_id' => 6,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '489', 'unit' => 'ch', 'sub' => '360 kW'],
            ['label' => 'Batterie',  'value' => '94,5', 'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '753', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '4,0', 'unit' => 's', 'sub' => '210 km/h'],
            ['label' => 'Poids',     'value' => '2 200','unit' => 'kg', 'sub' => 'Coffre 480 L'],
        ],
        'specs_motorisation' => ['489 ch (360 kW)', '700 Nm', 'Intégrale (4MATIC)', '210 km/h'],
        'specs_batterie' => [
            'capacite' => '94,5 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '753 km',
            'extra_name' => 'Architecture', 'extra_value' => '800V',
            'battery_kwh' => '94.5 kWh', 'battery_fill' => '87%',
        ],
        'specs_recharge' => ['8 h 30 (11 kW)', '22 min (10-80%, 330 kW)'],
        'specs_dimensions' => ['4 850 mm', '1 900 mm', '1 420 mm', '480 L'],
    ],
    'mercedes-EQC' => [
        'filename' => 'mercedes-EQC',
        'page_title' => 'Mercedes EQC — EcoDrive',
        'page_desc'  => 'Mercedes EQC, premier SUV électrique Mercedes. 419 km d\'autonomie, luxe et performance.',
        'page_url'   => 'voitures/mercedes-EQC.php',
        'page_image' => 'images/mercedes-eqc/mercedes-eqc.jpg',
        'jsonld' => ['brand' => 'Mercedes-Benz', 'price' => '280000'],
        'breadcrumb' => 'Mercedes EQC 400 4MATIC',
        'slider' => ['dir' => 'images/mercedes-eqc/', 'img' => 'mercedes-eqc.jpg', 'alt' => 'Mercedes EQC 400'],
        'price_display' => '280 000',
        'car_id' => 7,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '408', 'unit' => 'ch', 'sub' => '300 kW'],
            ['label' => 'Batterie',  'value' => '80',  'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '432', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '5,1', 'unit' => 's', 'sub' => '180 km/h'],
            ['label' => 'Poids',     'value' => '2 495','unit' => 'kg', 'sub' => 'Coffre 500 L'],
        ],
        'specs_motorisation' => ['408 ch (300 kW)', '760 Nm', 'Intégrale (4MATIC)', '180 km/h'],
        'specs_batterie' => [
            'capacite' => '80 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '432 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '80 kWh', 'battery_fill' => '74%',
        ],
        'specs_recharge' => ['7 h 30 (11 kW)', '30 min (10-80%, 110 kW)'],
        'specs_dimensions' => ['4 762 mm', '1 884 mm', '1 624 mm', '500 L'],
    ],
    'mg4' => [
        'filename' => 'mg4',
        'page_title' => 'MG4 — EcoDrive',
        'page_desc'  => 'MG4, berline électrique sportive au prix accessible. Jusqu\'à 450 km d\'autonomie. Essai EcoDrive.',
        'page_url'   => 'voitures/mg4.php',
        'page_image' => 'images/mg4/mg-4-urban.jpg',
        'jsonld' => ['brand' => 'MG', 'price' => '54950'],
        'breadcrumb' => 'MG4 Urban',
        'slider' => ['dir' => 'images/mg4/', 'img' => 'mg-4-urban.jpg', 'alt' => 'MG4 Urban'],
        'price_display' => '54 950',
        'car_id' => 8,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '160', 'unit' => 'ch', 'sub' => '118 kW'],
            ['label' => 'Batterie',  'value' => '53,9', 'unit' => 'kWh', 'sub' => 'LFP'],
            ['label' => 'Autonomie', 'value' => '420', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '7,9', 'unit' => 's', 'sub' => '160 km/h'],
            ['label' => 'Poids',     'value' => '1 655','unit' => 'kg', 'sub' => 'Coffre 385 L'],
        ],
        'specs_motorisation' => ['160 ch (118 kW)', '250 Nm', 'Propulsion (RWD)', '160 km/h'],
        'specs_batterie' => [
            'capacite' => '53,9 kWh', 'type' => 'LFP', 'autonomie' => '420 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '43 kWh', 'battery_fill' => '40%',
        ],
        'specs_recharge' => ['6 h (11 kW)', '24 min (10-80%, 135 kW)'],
        'specs_dimensions' => ['4 287 mm', '1 836 mm', '1 504 mm', '385 L'],
    ],
    'Peugeot-e-208' => [
        'filename' => 'Peugeot-e-208',
        'page_title' => 'Peugeot e-208 — EcoDrive',
        'page_desc'  => 'Peugeot e-208, citadine électrique chic et agile. Autonomie 362 km WLTP. Découvrez-la.',
        'page_url'   => 'voitures/Peugeot-e-208.php',
        'page_image' => 'images/peugeot-e-208/E-208_gallery_exterior_3_D_1920x1080.jpg',
        'jsonld' => ['brand' => 'Peugeot', 'price' => '80000'],
        'breadcrumb' => 'Peugeot e-208',
        'slider' => ['dir' => 'images/peugeot-e-208/', 'img' => 'E-208_gallery_exterior_3_D_1920x1080.jpg', 'alt' => 'Peugeot e-208'],
        'price_display' => '80 000',
        'car_id' => 9,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '156', 'unit' => 'ch', 'sub' => '115 kW'],
            ['label' => 'Batterie',  'value' => '54',  'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '433', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '8,1', 'unit' => 's', 'sub' => '150 km/h'],
            ['label' => 'Poids',     'value' => '1 530','unit' => 'kg', 'sub' => 'Coffre 311 L'],
        ],
        'specs_motorisation' => ['156 ch (115 kW)', '260 Nm', 'Traction (FWD)', '150 km/h'],
        'specs_batterie' => [
            'capacite' => '54 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '433 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '54 kWh', 'battery_fill' => '50%',
        ],
        'specs_recharge' => ['5 h (11 kW)', '25 min (10-80%, 100 kW)'],
        'specs_dimensions' => ['4 055 mm', '1 745 mm', '1 430 mm', '311 L'],
    ],
    'Porsche-Taycan' => [
        'filename' => 'Porsche-Taycan',
        'page_title' => 'Porsche Taycan — EcoDrive',
        'page_desc'  => 'Porsche Taycan, berline électrique de haute performance. 0-100 en 2,8s. Réservez votre essai.',
        'page_url'   => 'voitures/Porsche-Taycan.php',
        'page_image' => 'images/porsche-taycan/porsche-taycan-taycan-91005.webp',
        'jsonld' => ['brand' => 'Porsche', 'price' => '448000'],
        'breadcrumb' => 'Porsche Taycan 2026',
        'slider' => ['dir' => 'images/porsche-taycan/', 'img' => 'porsche-taycan-taycan-91005.webp', 'alt' => 'Porsche Taycan'],
        'price_display' => '448 000',
        'car_id' => 10,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '408', 'unit' => 'ch', 'sub' => '300 kW'],
            ['label' => 'Batterie',  'value' => '89',  'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '503', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '4,8', 'unit' => 's', 'sub' => '230 km/h'],
            ['label' => 'Poids',     'value' => '2 200','unit' => 'kg', 'sub' => 'Coffre 407 L'],
        ],
        'specs_motorisation' => ['408 ch (300 kW)', '410 Nm', 'Propulsion (RWD)', '230 km/h'],
        'specs_batterie' => [
            'capacite' => '89 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '503 km',
            'extra_name' => 'Architecture', 'extra_value' => '800V',
            'battery_kwh' => '89 kWh', 'battery_fill' => '82%',
        ],
        'specs_recharge' => ['9 h 30 (11 kW)', '18 min (10-80%)'],
        'specs_dimensions' => ['4 963 mm', '1 966 mm', '1 395 mm', '407 L'],
    ],
    'Tesla-Model-3' => [
        'filename' => 'Tesla-Model-3',
        'page_title' => 'Tesla Model 3 2026 — EcoDrive',
        'page_desc'  => 'Découvrez la Tesla Model 3 2026, berline électrique avec 702 km d\'autonomie. Réservez votre essai EcoDrive en Tunisie.',
        'page_url'   => 'voitures/Tesla-Model-3.php',
        'page_image' => 'images/tesla-model-3/tesla-model3.jpg',
        'jsonld' => ['brand' => 'Tesla', 'price' => '147000'],
        'breadcrumb' => 'Tesla Model 3 2026',
        'slider' => ['dir' => 'images/tesla-model-3/', 'img' => 'tesla-model3.jpg', 'alt' => 'Tesla Model 3'],
        'price_display' => '147 000',
        'car_id' => 11,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '498', 'unit' => 'ch', 'sub' => '366 kW'],
            ['label' => 'Batterie',  'value' => '82',  'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '702', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '3,1', 'unit' => 's', 'sub' => '262 km/h'],
            ['label' => 'Poids',     'value' => '1 844','unit' => 'kg', 'sub' => 'Coffre 594 L'],
        ],
        'specs_motorisation' => ['498 ch (366 kW)', '510 Nm', 'Intégrale (AWD)', '262 km/h'],
        'specs_batterie' => [
            'capacite' => '82 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '702 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '82 kWh', 'battery_fill' => '75%',
        ],
        'specs_recharge' => ['8 h 30 (11 kW)', '20 min (10-80%, 250 kW)'],
        'specs_dimensions' => ['4 720 mm', '1 933 mm', '1 441 mm', '594 L'],
    ],
    'Tesla-Model-S-Plaid' => [
        'filename' => 'Tesla-Model-S-Plaid',
        'page_title' => 'Tesla Model S Plaid — EcoDrive',
        'page_desc'  => 'Tesla Model S Plaid, la berline électrique la plus puissante. 1 020 ch, 0-100 en 2,1s. Essai chez EcoDrive.',
        'page_url'   => 'voitures/Tesla-Model-S-Plaid.php',
        'page_image' => 'images/tesla-model-s-plaid/tesla-model-s-plaid.jpg',
        'jsonld' => ['brand' => 'Tesla', 'price' => '359400'],
        'breadcrumb' => 'Tesla Model S Plaid 2026',
        'slider' => ['dir' => 'images/tesla-model-s-plaid/', 'img' => 'tesla-model-s-plaid.jpg', 'alt' => 'Tesla Model S Plaid'],
        'price_display' => '359 400',
        'car_id' => 12,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '1 020','unit' => 'ch', 'sub' => '760 kW'],
            ['label' => 'Batterie',  'value' => '100',  'unit' => 'kWh', 'sub' => 'Lithium-ion NCA'],
            ['label' => 'Autonomie', 'value' => '600', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '2,1', 'unit' => 's', 'sub' => '322 km/h'],
            ['label' => 'Poids',     'value' => '2 175','unit' => 'kg', 'sub' => 'Coffre 793 L'],
        ],
        'specs_motorisation' => ['1 020 ch (760 kW)', '1 420 Nm', 'Intégrale (AWD)', '322 km/h'],
        'specs_batterie' => [
            'capacite' => '100 kWh', 'type' => 'Lithium-ion NCA', 'autonomie' => '600 km',
            'extra_name' => 'Émissions CO₂', 'extra_value' => '0 g/km CO₂',
            'battery_kwh' => '100 kWh', 'battery_fill' => '92%',
        ],
        'specs_recharge' => ['9 h (11 kW)', '15 min (10-80%, 250 kW)'],
        'specs_dimensions' => ['5 021 mm', '1 987 mm', '1 431 mm', '793 L'],
    ],
    'toyota-bz4x' => [
        'filename' => 'toyota-bz4x',
        'page_title' => 'Toyota bZ4X — EcoDrive',
        'page_desc'  => 'Toyota bZ4X, SUV électrique fiable avec plateforme e-TNGA. Autonomie 500 km.',
        'page_url'   => 'voitures/toyota-bz4x.php',
        'page_image' => 'images/toyota-bz4x-73.1-kwh/toyota-bz4x-73.1-kwh-109445.webp',
        'jsonld' => ['brand' => 'Toyota', 'price' => '129800'],
        'breadcrumb' => 'Toyota bZ4X 73.1 kWh',
        'slider' => ['dir' => 'images/toyota-bz4x-73.1-kwh/', 'img' => 'toyota-bz4x-73.1-kwh-109445.webp', 'alt' => 'Toyota bZ4X 73.1 kWh'],
        'price_display' => '129 800',
        'car_id' => 13,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '227', 'unit' => 'ch', 'sub' => '167 kW'],
            ['label' => 'Batterie',  'value' => '73,1', 'unit' => 'kWh', 'sub' => 'Lithium-ion NMC'],
            ['label' => 'Autonomie', 'value' => '573', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '8,4', 'unit' => 's', 'sub' => '160 km/h'],
            ['label' => 'Poids',     'value' => '1 950','unit' => 'kg', 'sub' => 'Coffre 452 L'],
        ],
        'specs_motorisation' => ['227 ch (167 kW)', '270 Nm', 'Traction (FWD)', '160 km/h'],
        'specs_batterie' => [
            'capacite' => '73,1 kWh', 'type' => 'Lithium-ion NMC', 'autonomie' => '573 km',
            'extra_name' => 'Consommation', 'extra_value' => '14,3 kWh/100 km',
            'battery_kwh' => '73.1 kWh', 'battery_fill' => '67%',
        ],
        'specs_recharge' => ['7 h (11 kW)', '28 min (10-80%)'],
        'specs_dimensions' => ['4 690 mm', '1 860 mm', '1 650 mm', '452 L'],
    ],
    'Geely-EX2' => [
        'filename' => 'Geely-EX2',
        'page_title' => 'Geely EX2 — EcoDrive',
        'page_desc'  => 'Geely EX2, SUV électrique compact au excellent rapport qualité-prix. Autonomie et confort garantis.',
        'page_url'   => 'voitures/Geely-EX2.php',
        'page_image' => 'images/geely-ex2/geely-ex2-39.4-kwh-max-101691.webp',
        'jsonld' => ['brand' => 'Geely', 'price' => '52000'],
        'breadcrumb' => 'Geely EX2',
        'slider' => ['dir' => 'images/geely-ex2/', 'img' => 'geely-ex2-39.4-kwh-max-101691.webp', 'alt' => 'Geely EX2'],
        'price_display' => '52 000',
        'car_id' => 14,
        'highlights' => [
            ['label' => 'Puissance', 'value' => '115', 'unit' => 'ch', 'sub' => '85 kW'],
            ['label' => 'Batterie',  'value' => '39,4', 'unit' => 'kWh', 'sub' => 'LFP'],
            ['label' => 'Autonomie', 'value' => '325', 'unit' => 'km', 'sub' => 'Cycle WLTP'],
            ['label' => '0-100 km/h','value' => '10,2','unit' => 's', 'sub' => '130 km/h'],
            ['label' => 'Poids',     'value' => '1 380','unit' => 'kg', 'sub' => 'Coffre 400 L'],
        ],
        'specs_motorisation' => ['115 ch (85 kW)', '150 Nm', 'Propulsion (RWD)', '130 km/h'],
        'specs_batterie' => [
            'capacite' => '39,4 kWh', 'type' => 'LFP', 'autonomie' => '325 km',
            'extra_name' => 'Consommation', 'extra_value' => '12,1 kWh/100 km',
            'battery_kwh' => '39.4 kWh', 'battery_fill' => '36%',
        ],
        'specs_recharge' => ['5 h 30 (7 kW)', '21 min (30-80%)'],
        'specs_dimensions' => ['4 005 mm', '1 760 mm', '1 570 mm', '400 L'],
    ],
];
